# Generated by Django 6.0.3 on 2026-04-01 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Компания производитель')),
            ],
            options={
                'verbose_name': 'Компания производитель',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Component_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название компонента')),
                ('description', models.CharField(max_length=1000, verbose_name='Характеристики компонента')),
                ('img', models.ImageField(upload_to='component_covers/', verbose_name='Изображение компонента')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_project.brand', verbose_name='Компания производитель')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_project.component_category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': ('Компонент',),
                'verbose_name_plural': 'Компоненты',
            },
        ),
    ]
