# Generated by Django 6.0.3 on 2026-04-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conputer', '0002_component_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='component_category',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='category_covers/', verbose_name='Изображение компонента'),
        ),
    ]
