# Generated by Django 6.0.3 on 2026-04-13 16:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conputer', '0003_component_category_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component_category',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='component_covers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])], verbose_name='Изображение (JPG, PNG, SVG)'),
        ),
        migrations.CreateModel(
            name='PCBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название сборки')),
                ('user_name', models.CharField(blank=True, max_length=100, verbose_name='Имя автора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('storage_primary_quantity', models.PositiveIntegerField(default=1, verbose_name='Количество накопителей 1')),
                ('storage_second_quantity', models.PositiveIntegerField(default=1, verbose_name='Количество накопителей 2')),
                ('coollerCase_quantity', models.PositiveIntegerField(default=1, verbose_name='Количество вентиляторов')),
                ('case', models.ForeignKey(blank=True, limit_choices_to={'category__name__iexact': 'Корпус'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_case', to='conputer.component', verbose_name='Корпус')),
                ('cooller', models.ForeignKey(blank=True, limit_choices_to={'category__name__iexact': 'Куллер для процессора'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_cooller', to='conputer.component', verbose_name='Кулер для процессора')),
                ('coollerCase', models.ForeignKey(blank=True, limit_choices_to={'category__name__iexact': 'Корпусный вентилятор'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_coollerCase', to='conputer.component', verbose_name='Корпусный вентилятор')),
                ('cpu', models.ForeignKey(blank=True, limit_choices_to={'category__name__iexact': 'Процессоры'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_cpu', to='conputer.component', verbose_name='Процессор')),
                ('gpu', models.ForeignKey(blank=True, limit_choices_to={'category__name__iexact': 'Видеокарта'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_gpu', to='conputer.component', verbose_name='Видеокарта')),
                ('motherboard', models.ForeignKey(blank=True, limit_choices_to={'category__name__iexact': 'Материнская плата'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_mboard', to='conputer.component', verbose_name='Материнская плата')),
                ('powerSupply', models.ForeignKey(blank=True, limit_choices_to={'category__name__iexact': 'Блок питания'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_powerSupply', to='conputer.component', verbose_name='Блок питания')),
                ('ram', models.ForeignKey(blank=True, limit_choices_to={'category__name__iexact': 'Оперативная память'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_ram', to='conputer.component', verbose_name='Оперативная память')),
                ('storage_primary', models.ForeignKey(blank=True, limit_choices_to={'category__name__iexact': 'Накопитель'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_storage_primary', to='conputer.component', verbose_name='Накопитель 1')),
                ('storage_second', models.ForeignKey(blank=True, limit_choices_to={'category__name__iexact': 'Накопитель'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_storage_second', to='conputer.component', verbose_name='Накопитель 2')),
            ],
            options={
                'verbose_name': 'Сборка ПК',
                'verbose_name_plural': 'Сборки ПК',
            },
        ),
    ]
