# Generated by Django 6.0.3 on 2026-04-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conputer', '0004_alter_component_category_img_pcbuild'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcbuild',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='build_photos/', verbose_name='Фото сборки'),
        ),
    ]
