# Generated by Django 6.0.3 on 2026-04-19 13:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conputer', '0005_pcbuild_main_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcbuild',
            name='user_name',
        ),
        migrations.AddField(
            model_name='pcbuild',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='pcbuild',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовать в сообществе'),
        ),
        migrations.AlterField(
            model_name='pcbuild',
            name='coollerCase_quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Количество вентиляторов'),
        ),
        migrations.AlterField(
            model_name='pcbuild',
            name='main_photo',
            field=models.FileField(blank=True, null=True, upload_to='component_covers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])], verbose_name='Изображение (JPG, PNG, SVG)'),
        ),
    ]
