# Generated by Django 6.0.3 on 2026-04-20 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conputer', '0006_remove_pcbuild_user_name_pcbuild_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcbuild',
            name='cooller',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__name__iexact': 'Кулер для процессора'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_cooller', to='conputer.component', verbose_name='Кулер для процессора'),
        ),
        migrations.AlterField(
            model_name='pcbuild',
            name='cpu',
            field=models.ForeignKey(blank=True, limit_choices_to={'category__name__iexact': 'Процессор'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_cpu', to='conputer.component', verbose_name='Процессор'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('cart', 'В корзине'), ('pending', 'Оформлен'), ('shipped', 'В пути'), ('done', 'Завершен')], default='cart', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conputer.pcbuild', verbose_name='Сборка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
        ),
    ]
