# Generated by Django 6.0.3 on 2026-04-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conputer', '0007_alter_pcbuild_cooller_alter_pcbuild_cpu_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата доставки'),
        ),
    ]
