# Generated by Django 6.0.3 on 2026-04-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conputer', '0008_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'В корзине'), ('favorite', 'В избранном'), ('pending', 'Оформлен'), ('shipped', 'В пути'), ('done', 'Завершен')], default='cart', max_length=20),
        ),
    ]
