# Generated by Django 6.0.3 on 2026-04-21 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conputer', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='preview_image',
            field=models.FileField(blank=True, null=True, upload_to='previews/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])], verbose_name='Картинка для превью (PNG/SVG)'),
        ),
    ]
